FROM node:16.14.2-alpine3.15 as builder

WORKDIR /usr/src/app

COPY . .

RUN npm ci && npm run build:local

FROM nginx:1.23.2-alpine

COPY --from=builder /usr/src/app/build /usr/share/nginx/html

COPY nginx/default.conf /etc/nginx/conf.d

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]